remote_theme: samarsault/plainwhite-jekyll

title: DDAONG's Page
author: DDDAONG
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

plainwhite:
  name: dddaong
  tagline: Network Eng.
  date_format: "%b %-d, %Y"

  social_links:
    #twitter: Don'tHave
    github: dddaong.github.io
    #linkedIn: Don'tHave
    #rss: rss
    #dribbble: Don'tHave
    #flickr:   Don'tHave
    #instagram: Don'tHave
    #pinterest: Don'tHave
    #youtube: Don'tHave
    #facebook: Don'tHave
    #soundcloud: Don'tHave
    #telegram: Don'tHave
    #gitlab: Don'tHave
    #email: Don'tHave

  navigation:
    - title: Administrate BIG-IP
      url: "/bigip/admin"
    - title: NGINX+ Ingress Controller
      url: "/nginxinc"
    - title: NGINX Controller + APIM
      url: "/nginxapim"
  
  sitemap: true
  portfolio_image:      "assets/portfolio.png"
  html_lang: "kr"
  dark_mode: false
  
plugins:
  - jekyll-seo-tag
