remote_theme: samarsault/plainwhite-jekyll

plainwhite:
  name: dddaong
  tagline: Network Eng.
  date_format: "%b %-d, %Y"

  social_links:
    twitter: Don'tHave
    github: dddaong.github.io
    linkedIn: Don'tHave

  navigation:
    - title: Administrate BIG-IP
      url: "/bigip/admin"
    - title: NGINX+ Ingress Controller
      url: "/nginxinc"
    - title: NGINX Controller + APIM
      url: "/nginxapim"
  sitemap: true
  portfolio_image:      "assets/portfolio.png"
  html_lang: "kr"
  dark_mode: false
