name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install jinja2>=3.0.2
      - run: pip install markdown>=3.2
      - run: pip install mkdocs>=1.3.0
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions>=1.0.3
      - run: pip install pygments>=2.12
      - run: pip install pymdown-extensions>=9.4
      - run: pip install mdx_include
      - run: mkdocs gh-deploy --force
